<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Enzo.Diagrams.Core\Enzo.Diagrams.Core.csproj" />
    <ProjectReference Include="..\Enzo.Diagrams.Language\Enzo.Diagrams.Language.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.148.0" />
    <PackageReference Include="Svg.Skia" Version="5.2.3" />
  </ItemGroup>

</Project>
